---
# - name: Set hostname
#   hostname:
#     name: "{{ inventory_hostname }}"
#     use: debian
- name: Install Python 3
  apt:
    name: python3
    state: present
- name: Install pip
  apt:
    name: python3-pip
    state: present
- name: Pull vaulty repo
  git:
    repo: 'https://github.com/aksiksi/vaulty.git'
    dest: /var/www/vaulty
