language: rust
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - language: rust
      before_script:
        - cd vaulty-mail
      script:
        - cargo build
        - cargo test
      cache: cargo
