trigger:
  branches:
    include:
      - master
  paths:
    include:
      - vaulty-mail

pool:
  vmImage: 'ubuntu-latest'

# TODO: Add step to test vaulty-web
jobs:
- job: Test
  steps:
  - script: |
      cd vaulty-mail
      DROPBOX_TOKEN=$(DROPBOX_TOKEN) cargo test
      cd ..
    displayName: 'Build vaulty and run tests'
