trigger:
  branches:
    include:
      - master
  paths:
    include:
      - vaulty-mail

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd vaulty-mail
    cargo build
    DROPBOX_TOKEN=$(DROPBOX_TOKEN) cargo test
  displayName: 'Build vaulty and run tests'
