trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd vaulty-mail
    cargo build
    cargo test
  displayName: 'Build vaulty and run tests'
  env:
    DROPBOX_TOKEN: $(DROPBOX_TOKEN)