---
- name: Setup webserver
  hosts: webservers
  tasks:
    # - name: Install nginx
    #   apt:
    #     name: nginx
    #     state: present
    - name: Copy vaulty_mgr to /usr/bin
      copy:
        src: vaulty-mail/target/release/vaulty_mgr
        dest: /usr/bin
        mode: u=rwx,g=rwx,o=rwx
