# Run: ansible-playbook -i ~/hosts provision.yml
---
- name: Common setup
  hosts: "*"
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
    - name: Install rsync
      apt:
        name: rsync
        state: present

# We need to provision vaulty-web first to ensure that DB is
# setup and ready to go for Postfix virtual mailboxes
- name: Provision DB
  hosts: dbservers
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Pull vaulty repo
      git:
        repo: 'https://github.com/aksiksi/vaulty.git'
        dest: /var/www/vaulty

- name: Provision vaulty-web
  hosts: webservers
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
        use: debian
    - name: Install Python 3
      apt:
        name: python3
        state: present
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    - name: Pull vaulty repo
      git:
        repo: 'https://github.com/aksiksi/vaulty.git'
        dest: /var/www/vaulty

- name: Provision vaulty-mail
  hosts: mailservers
  tasks:
    - name: Build "vaulty-filter" and "vaulty-server" (release)
      local_action:
        module: shell
        cmd: cargo build --release
        chdir: vaulty-mail
    - name: Copy "vaulty_server" to "/usr/bin"
      copy:
        src: vaulty-mail/target/release/vaulty_server
        dest: /usr/bin
        mode: u=rwx,g=rwx,o=rwx
    - name: Copy "vaulty_filter" to "/usr/bin"
      copy:
        src: vaulty-mail/target/release/vaulty_filter
        dest: /usr/bin
        mode: u=rwx,g=rwx,o=rwx
    - name: Install Postfix
      apt:
        name: postfix
        state: present
    - name: Ensure group "vmail" exists
      group:
        name: vmail
        gid: 5000
        state: present
    - name: Create "vmail" user and assign to "vmail" group
      user:
        name: vmail
        uid: 5000
        group: vmail
        home: /var/vmail
        move_home: true
        create_home: true
        state: present
    - name: Copy Postfix configs to "/etc/postfix"
      copy:
        src: "{{ item }}"
        dest: /etc/postfix
      loop:
        - vaulty-mail/setup/postfix/master.cf
        - vaulty-mail/setup/postfix/main.cf
        - vaulty-mail/setup/postfix/vmail
        - vaulty-mail/setup/postfix/virtual
    # vmail: converts a recipient mail address to a mailbox
    # virtual: specifies certain virtual addresses that need forwarding
    # TODO: Convert vmail to use Postgres lookup
    - name: Rebuild virtual mailbox and alias maps
      shell: |
        /usr/sbin/postmap /etc/postfix/vmail
        /usr/sbin/postmap /etc/postfix/virtual
    - name: Rebuild vmail DB
      shell: /usr/sbin/postmap /etc/postfix/vmail
    - name: Reload Postfix configs
      shell: postfix reload
