---
- name: Install git
  apt:
    name: git
    state: present
- name: Install rsync
  apt:
    name: rsync
    state: present
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
- name: Copy basic fail2ban SSH config
  copy:
    src: ../files/jail.local
    dest: /etc/fail2ban/jail.local
    mode: u=rw,g=rw,o=rw
- name: Reload fail2ban
  service:
    name: fail2ban
    state: reloaded
