---
- name: Install git
  apt:
    name: git
    state: present
- name: Install rsync
  apt:
    name: rsync
    state: present
- name: Copy basic SSH config
  copy:
    src: ../files/sshd_config
    dest: /etc/ssh/
    mode: u=rw,g=r,o=r
- name: Restart sshd
  service:
    name: sshd
    state: reloaded
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
- name: Copy basic fail2ban SSH config
  copy:
    src: ../files/jail.local
    dest: /etc/fail2ban/jail.local
    mode: u=rw,g=r,o=r
- name: Reload fail2ban
  service:
    name: fail2ban
    state: reloaded
