---
- name: Install git
  apt:
    name: git
    state: present
- name: Install rsync
  apt:
    name: rsync
    state: present
- name: Install UFW
  apt:
    name: ufw
    state: present
- name: Copy basic SSH config
  copy:
    src: ../files/sshd_config
    dest: /etc/ssh/
    mode: u=rw,g=r,o=r
- name: Restart sshd
  service:
    name: sshd
    state: reloaded
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
- name: Copy basic fail2ban SSH config
  copy:
    src: ../files/jail.local
    dest: /etc/fail2ban/jail.local
    mode: u=rw,g=r,o=r
- name: Reload fail2ban
  service:
    name: fail2ban
    state: reloaded
# Common firewall rules across all machines
- name: Allow HTTP
  ufw:
    rule: allow
    port: http
- name: Allow HTTPS
  ufw:
    rule: allow
    port: https
- name: Allow SSH
  ufw:
    rule: allow
    port: ssh
- name: Enable UFW
  ufw:
    state: enabled
    policy: reject
