---
- name: Install Postfix
  apt:
    name: postfix
    state: present
- name: Set machine hostname
  hostname:
    name: "{{ inventory_hostname }}"
- name: Ensure mail group exists
  group:
    name: "{{ mail_group }}"
    gid: "{{ mail_gid }}"
    state: present
- name: Create mail user and assign to group
  user:
    name: "{{ mail_user }}"
    password: "{{ mail_pass }}"
    uid: "{{ mail_uid }}"
    groups: "{{ mail_group }}"
    home: "{{ mail_dir }}"
    create_home: true
    state: present
- name: Create maildir for user
  file:
    path: "/var/mail/{{ mail_user }}"
    state: directory
    mode: '0755'
    owner: "{{ mail_user }}"
    group: "{{ mail_group }}"
- name: Install Postfix pgsql
  apt:
    name: postfix-pgsql
    state: present
- name: Install Postfix SPF policy server
  apt:
    name: postfix-policyd-spf-python
    state: present
- name: Install Cyrus for SASL
  apt:
    name: sasl2-bin
    state: present
- name: Copy main SASL startup config
  copy:
    src: ../files/sasl/saslauthd
    dest: /etc/default/saslauthd
  tags:
    - update
- name: Copy SASL config for DB auth
  copy:
    src: ../files/sasl/smtpd.conf
    dest: /usr/lib/sasl2/smtpd.conf
  tags:
    - update
- name: Add "postfix" user to SASL group
  user:
    name: postfix
    groups:
      - sasl
    append: true
- name: Adjust UNIX socket permissions to allow Postfix access
  file:
    path: /var/run/saslauthd/
    mode: g+rx

# NOTE: You still need to create the SASL auth DB and add users
# You can do that with this command:
# saslpasswd2 -c -u example.net test
# >>> enter password
# Login with: test@example.net
# To test:
# testsaslauthd -u "test" -r example.net -p "test"

- name: Build "vaulty-filter" and "vaulty-server" (release)
  local_action:
    module: shell
    cmd: cargo build --release
    chdir: ../vaulty-mail
  tags:
    - test
    - update
- name: Copy "vaulty_server" to "/usr/bin"
  copy:
    src: ../vaulty-mail/target/release/vaulty_server
    dest: /usr/bin
    mode: u=rwx,g=rwx,o=rwx
  tags:
    - test
    - update
- name: Copy "vaulty_filter" to "/usr/bin"
  copy:
    src: ../vaulty-mail/target/release/vaulty_filter
    dest: /usr/bin
    mode: u=rwx,g=rwx,o=rwx
  tags:
    - test
    - update
- name: Install certbot
  apt:
    name: certbot
    state: present
# NOTE: Port 80 must not be taken (i.e., vaulty-web must be on another machine)
- name: Configure and enable certbot
  command: sudo certbot certonly --standalone -d "{{ inventory_hostname }}" --non-interactive --agree-tos -m "{{ vaulty_postmaster }}"
  args:
    creates: "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"
# NOTE: vmail user must have access to cert directories...
# Otherwise, add vmail to sudo
- name: Create crontab to renew certs
  cron:
    name: "Renew LetsEncrypt certs"
    minute: "0"
    hour: "0"
    job: "/usr/bin/certbot renew > /dev/null"
- name: Add certbot hook to reload Postfix on cert renewal
  lineinfile:
    path: "/etc/letsencrypt/renewal/{{ inventory_hostname }}.conf"
    line: "renew_hook = sudo systemctl reload postfix"
    state: present
- name: Copy Postfix configs to "/etc/postfix"
  copy:
    src: "{{ item }}"
    dest: /etc/postfix
  loop:
    - ../files/postfix/master.cf
    - ../files/postfix/virtual
  tags:
    - update
- name: Template Postfix "main.cf"
  template:
    src: ../templates/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: "{{ mail_user }}"
    group: "{{ mail_group }}"
    mode: u=rw,g=r,o=r
  tags:
    - update
- name: Template Postfix PGSQL virtual mapping file
  template:
    src: ../templates/postfix/pgsql-vmail.cf.j2
    dest: /etc/postfix/pgsql-vmail.cf
    owner: "{{ mail_user }}"
    group: "{{ mail_group }}"
    mode: u=rw,g=r,o=r
  tags:
    - update
- name: Template Postfix PGSQL virtual aliases file
  template:
    src: ../templates/postfix/pgsql-valiases.cf.j2
    dest: /etc/postfix/pgsql-valiases.cf
    owner: "{{ mail_user }}"
    group: "{{ mail_group }}"
    mode: u=rw,g=r,o=r
  tags:
    - update
- name: Reload Postfix configs
  shell: postfix reload
  tags:
    - update
- name: Restart SASL
  systemd:
    name: saslauthd
    state: restarted
  tags:
    - update
- name: Copy "vaulty_server" systemd unit
  copy:
    src: ../files/vaulty.service
    dest: /etc/systemd/system/
  tags:
    - test
    - update
- name: Copy "vaulty_server" env file
  copy:
    src: ../files/vaulty.env
    dest: /etc/vaulty/
  tags:
    - test
    - update
- name: Template "vaulty_server" config file
  template:
    src: ../templates/vaulty.toml.j2
    dest: /etc/vaulty/vaulty.toml
    owner: "{{ mail_user }}"
    group: "{{ mail_group }}"
    mode: u=rw,g=r,o=r
  tags:
    - test
    - update
- name: Enable and start vaulty service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: vaulty
  tags:
    - test
    - update
