---
- name: Install Postfix pgsql
  apt:
    name: postfix-pgsql
    state: present
- name: Build "vaulty-filter" and "vaulty-server" (release)
  local_action:
    module: shell
    cmd: cargo build --release
    chdir: ../vaulty-mail
- name: Copy "vaulty_server" to "/usr/bin"
  copy:
    src: ../vaulty-mail/target/release/vaulty_server
    dest: /usr/bin
    mode: u=rwx,g=rwx,o=rwx
- name: Copy "vaulty_filter" to "/usr/bin"
  copy:
    src: ../vaulty-mail/target/release/vaulty_filter
    dest: /usr/bin
    mode: u=rwx,g=rwx,o=rwx
- name: Install Postfix
  apt:
    name: postfix
    state: present
- name: Ensure mail group exists
  group:
    name: "{{ mail_group }}"
    gid: "{{ mail_gid }}"
    state: present
- name: Create mail user and assign to group
  user:
    name: "{{ mail_user }}"
    uid: "{{ mail_uid }}"
    group: "{{ mail_group }}"
    home: "{{ mail_dir }}"
    move_home: true
    create_home: true
    state: present
- name: Copy Postfix configs to "/etc/postfix"
  copy:
    src: "{{ item }}"
    dest: /etc/postfix
  loop:
    - ../files/postfix/master.cf
    - ../files/postfix/virtual
- name: Template Postfix "main.cf"
  template:
    src: ../templates/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: vmail
    group: vmail
    mode: u=rw,g=r,o=r
- name: Template Postfix PGSQL virtual mapping file
  template:
    src: ../templates/postfix/pgsql-vmail.cf.j2
    dest: /etc/postfix/pgsql-vmail.cf
    owner: vmail
    group: vmail
    mode: u=rw,g=r,o=r
- name: Rebuild virtual alias maps
  shell: |
    /usr/sbin/postmap /etc/postfix/virtual
- name: Reload Postfix configs
  shell: postfix reload
- name: Copy "vaulty_server" systemd unit
  copy:
    src: ../files/vaulty.service
    dest: /etc/systemd/system/
- name: Copy "vaulty_server" env file
  copy:
    src: ../files/vaulty.env
    dest: /etc/vaulty/
- name: Template "vaulty_server" config file
  template:
    src: ../templates/vaulty.toml.j2
    dest: /etc/vaulty/vaulty.toml
    owner: vmail
    group: vmail
    mode: u=rw,g=r,o=r
- name: Enable and start vaulty service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: vaulty
