---
- name: Install Postgres
  apt:
    pkg:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes
- name: Create DB user and set password
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    expires: infinity
- name: Create "vaulty" DB
  become: yes
  become_user: postgres
  postgresql_db:
    name: vaulty
    owner: "{{ db_user }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
- name: Adjust DB user privileges
  become: yes
  become_user: postgres
  postgresql_user:
    db: vaulty
    name: "{{ db_user }}"
    priv: "CONNECT"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
- name: Copy DB schema
  copy:
    src: ../vaulty-db/schema.sql
    dest: /etc/vaulty/
    mode: u=rw,g=rw,o=r
- name: Apply schema
  become: yes
  become_user: postgres
  shell: psql -d vaulty -U {{ db_user }} -f /etc/vaulty/schema.sql
- name: Pull vaulty repo
  git:
    repo: 'https://github.com/aksiksi/vaulty.git'
    dest: /var/www/vaulty
